// Contenu du cours "Fondamentaux du marketing" (L2 Éco-Gestion).
// Syntaxe : ['h1'|'h2'|'h3', titre] · ['p', texte] · ['b', puce] · ['b2', sous-puce]
// ['img', fichier, largeurCm, légende] · ['table', [entêtes], [[ligne], ...]]
// ['ret', [points à retenir]] · ['note', texte] · ['glo', terme, définition]
// **gras** est accepté dans les textes.

module.exports = [
  // =====================================================================
  ['h1', 'Partie 1 – Fondamentaux du marketing (séances 1 à 5)'],
  // =====================================================================

  ['h2', 'Introduction au marketing'],

  ['h3', 'La naissance du concept marketing'],
  ['p', 'Le marketing est le fruit d’une évolution en trois temps de l’orientation des entreprises :'],
  ['b', '**Orientation production** : produire en quantité ; la demande dépasse l’offre, tout se vend.'],
  ['b', '**Orientation vente** : l’offre rattrape la demande ; il faut pousser les produits (force de vente, publicité).'],
  ['b', '**Orientation marketing** : partir des besoins du client pour concevoir l’offre.'],
  ['p', 'Question posée en cours : **influence = manipulation ?** Le marketing cherche à influencer les comportements ; la frontière avec la manipulation est un enjeu éthique.'],

  ['h3', 'Les champs du marketing'],
  ['table', ['Question', 'Déclinaisons'], [
    ['Quoi ?', 'Biens (tangibles ou non : téléphone, ebook), services (streaming, banque), expériences (escape game), causes (marketing social : anti-tabac), personnes (personal branding, politique), lieux (marketing territorial : ville de Lyon), événements (JO, Festival de Cannes)'],
    ['À qui ?', 'B2C (aux particuliers) / B2B (aux professionnels)'],
    ['Où ?', 'Local (boulangerie), régional/national, international (McDonald’s), global (Apple, Nike)'],
    ['Comment ?', 'Relationnel, digital, expérientiel/sensoriel, événementiel, d’influence'],
    ['Avec quoi ?', 'Comportement du consommateur, data marketing, neuromarketing'],
  ]],

  ['h3', 'Définition et valeur perçue'],
  ['p', '**Définition (Mercator)** : « Stratégie d’adaptation des organisations à des marchés concurrentiels pour influencer en leur faveur le comportement des publics dont elles dépendent, par une offre dont la valeur perçue est supérieure à celle des concurrents, durablement. »'],
  ['p', '➔ En bref : proposer une offre qui a **plus de valeur que celle des concurrents aux yeux des cibles**.'],
  ['p', '**Valeur perçue = Bénéfices perçus – Coûts perçus**. Exemple du cours : l’eau du robinet face aux nombreuses marques d’eau en bouteille, que l’on paie pourtant plus cher.'],
  ['img', 'c1_7.png', 12, 'Valeur perçue : un même besoin (boire de l’eau), des valeurs perçues différentes'],

  ['h3', 'La démarche marketing'],
  ['table', ['1. Analyse du marché', '2. Marketing stratégique', '3. Marketing mix', '4. Plan marketing'], [
    ['Environnement\nOffre\nDemande', 'Segmentation\nCiblage\nPositionnement', 'Produit\nPrix\nDistribution\nCommunication', 'Actions\nBudget\nPlanning'],
  ]],

  ['ret', [
    'Évolution : production → vente → marketing.',
    'Définition Mercator : offre à valeur perçue supérieure à celle des concurrents, durablement.',
    'Valeur perçue = bénéfices perçus – coûts perçus.',
    'Démarche : analyse du marché → stratégie (segmentation, ciblage, positionnement) → mix (4P) → plan.',
  ]],

  // ---------------------------------------------------------------------
  ['h2', '1. Analyse du marché'],
  ['p', 'Objectif : définir et connaître son marché. Un marché se caractérise par :'],
  ['b', '**Type de clients** : B2B, B2C, public, institutionnel.'],
  ['b', '**Zone géographique** : local, régional, national, international, global.'],
  ['b', '**Structure** : de niche, émergent, concurrentiel, saturé ; ouvert/fermé ; fragmenté/concentré.'],
  ['b', '**Stade** : naissance, développement, maturité, déclin.'],
  ['b', '**Niveau de dépendance** : induit, support/captif.'],
  ['b', '**Publics** : réel (actuel) / potentiel.'],
  ['b', '**Concurrence** : pertinente, principale, environnante, générique.'],

  ['h3', '1.1 Analyse de l’environnement'],
  ['p', '**Environnement interne** : ressources humaines, matérielles, financières, compétences spécifiques, avantages compétitifs.'],
  ['p', '**Environnement externe – le PESTEL** (macro-environnement) :'],
  ['table', ['P', 'E', 'S', 'T', 'E', 'L'], [
    ['Politique', 'Économique', 'Socioculturel', 'Technologique', 'Environnemental', 'Légal'],
  ]],
  ['p', '**Les 5 forces de Porter** (environnement du secteur) : rivalité entre les concurrents (au centre), menace des produits de substitution, menace des nouveaux entrants, pouvoir de négociation des fournisseurs, pouvoir de négociation des clients.'],
  ['p', '**Synthèse SWOT / TOWS** : le SWOT croise facteurs internes (forces, faiblesses) et externes (opportunités, menaces). Le TOWS en tire des pistes stratégiques :'],
  ['table', ['TOWS', 'Opportunités', 'Menaces'], [
    ['Forces', 'Leviers (Leverages)', 'Conflits (Conflicts)'],
    ['Faiblesses', 'Défis (Challenges)', 'Risques (Risks)'],
  ]],

  ['h3', '1.2 Analyse de l’offre'],
  ['b', '**Identifier son marché pertinent** : l’univers dans lequel l’offre est réellement en concurrence.'],
  ['b', '**Identifier ses concurrents directs et indirects** : Red Bull vs Monster (direct) ; Red Bull vs Coca-Cola (indirect).'],
  ['b', '**Répertorier toute l’offre** : usages, chaînes de distribution, goûts, marques, compositions et prix, tailles.'],
  ['b', '**Comprendre son marché** : structure (concentré : peu d’acteurs dominants / fragmenté : beaucoup de petits acteurs), type (niche, émergent, concurrentiel, saturé) et parts de marché.'],
  ['p', '**Part de marché = (Ventes de l’entreprise / Ventes totales du marché) × 100**'],

  ['h3', '1.3 Analyse de la demande'],
  ['p', '**Marché réel** = marché actuel. **Marché potentiel** = estimation du marché futur.'],
  ['img', 'c1_18.png', 13, 'Du marché total au marché réel de l’entreprise'],
  ['b', '**Marché total** : toute la population de référence.'],
  ['b', '**Marché potentiel de l’entreprise** = marché réel de l’entreprise (ses clients actuels) + prospects (clients de la concurrence + non-consommateurs relatifs).'],
  ['b', '**Non-consommateurs relatifs** : ne consomment pas encore mais pourraient le faire. **Non-consommateurs absolus** : ne consommeront jamais (impossibilité physique, morale…).'],
  ['p', 'Pour chaque marché on étudie : caractéristiques, taille, perspectives d’évolution.'],

  ['p', '**Quantifier la demande : les principaux indicateurs**'],
  ['table', ['Indicateur', 'Calcul / définition'], [
    ['Nombre d’acheteurs', 'NA'],
    ['Quantités achetées', 'QA'],
    ['Quantité moyenne par acheteur', 'QA / NA'],
    ['Ventes totales en volume', 'NA × QA/NA'],
    ['Valeur des achats', 'VA'],
    ['Valeur moyenne par acheteur', 'VA / NA'],
    ['Ventes totales en valeur', 'NA × VA/NA'],
    ['Fréquence d’achat', 'Nombre d’achats sur une période donnée'],
    ['Taux de pénétration', '% de clients potentiels ayant acheté au moins une fois sur la période = Marché réel / Marché potentiel'],
    ['Valeur à vie du client (CLV)', 'Valeur de l’ensemble des achats d’un type de produit qu’un client fait, en moyenne, pendant toute sa vie'],
  ]],

  ['p', '**Comprendre les consommateurs.** Attention : **besoin ≠ désir**. Le besoin est un manque ressenti ; le désir est la façon (le produit) de le satisfaire.'],
  ['img', 'c1_20.png', 8, 'La pyramide de Maslow et des exemples de marchés associés'],
  ['p', '**Processus de décision d’achat** : reconnaissance du besoin → recherche d’informations → évaluation des alternatives → décision d’achat → évaluation post-achat.'],
  ['p', '**Types d’achat** : routinier, impulsif, réfléchi/complexe, limité/intermédiaire.'],

  ['p', '**a) Facteurs psychologiques**'],
  ['b', '**Motivations** : hédonistes (plaisir), rationnelles, éthiques, oblatives (faire plaisir aux autres), d’auto-expression. **Freins** : inhibitions, risques perçus.'],
  ['b', '**Attitudes** : 3 dimensions – cognitive (connaître), affective (aimer), conative (agir) ➔ **hiérarchie des effets**. Deux types de traitement : central (réfléchi) ou périphérique (superficiel). + **Dissonance cognitive** (inconfort après un achat lorsque des doutes apparaissent).'],
  ['b', '**Image de soi** : recherche de congruence entre le « soi » et l’acte de consommation ; soi réel, soi idéal, soi social, soi social idéal.'],
  ['b', '**Implication** : degré d’importance accordé à une décision.'],
  ['b', '**Apprentissage** : conditionnement classique, conditionnement instrumental, apprentissage cognitif.'],
  ['b', '**Heuristiques et biais** : effet de halo (une caractéristique influence le jugement global), biais de confirmation (on retient ce qui confirme nos croyances), effet de rareté (ce qui est rare paraît plus désirable), effet d’ancrage (la première information sert de référence).'],
  ['p', '**b) Facteurs individuels** : âge et cycle de vie, profession et pouvoir d’achat, personnalité, style de vie.'],
  ['p', '**c) Facteurs sociaux et culturels**'],
  ['b', '**Culture** : détermine les besoins, influence les symboles, conditionne le rituel d’achat et d’usage.'],
  ['b', '**Sous-culture** (ethnique, religieuse, régionale, générationnelle…) ➔ marchés de niche.'],
  ['b', '**Classe sociale** : impacte le pouvoir d’achat et les préférences ; influence le comportement ostentatoire.'],
  ['b', '**Groupes** : groupes de référence, groupes de pairs, normes sociales, leaders d’opinion, rôles et statut social.'],
  ['p', '**d) Facteurs situationnels** : situation d’achat (moment, lieu, contexte physique et social), situation d’utilisation, situation temporelle, état émotionnel et financier temporaire.'],

  ['h3', '1.4 Les études marketing'],
  ['table', ['Études documentaires', 'Études qualitatives', 'Études quantitatives'], [
    ['Données secondaires (déjà existantes)', 'Données primaires : observations, entretiens individuels, focus groups…', 'Données primaires : questionnaires, panels, baromètres…'],
    ['➔ Défricher les tendances d’un marché', '➔ Comprendre en profondeur les consommateurs', '➔ Mesurer de façon représentative les usages et les évolutions'],
  ]],
  ['p', '**Études documentaires** : données internes (comptes clients, données de vente…) et externes (sites des concurrents, forums et avis en ligne, bases de données, sociétés d’études, presse, organismes publics).'],
  ['p', '**Études qualitatives** – 3 grandes méthodes : observation, entretiens (individuels ou de groupe), méthodes projectives.'],
  ['p', '**a) L’observation**'],
  ['table', ['Non-participante', 'Participante', 'Mixte'], [
    ['Directe : perceptible à l’œil nu (compter, chronométrer)', 'Ethnographie : comportements culturels ou sociaux', 'Ethnométhodologique : organisation des membres d’un groupe'],
    ['Avec matériel : non perceptible à l’œil nu (capteurs)', 'Netnographie : ethnographie en ligne', 'Narrative : comprendre le sens du comportement d’un individu'],
    ['', '', 'Scénarisée : mise en scène du répondant et de l’observateur'],
  ]],
  ['p', '**b) Les entretiens individuels** (du moins au plus structuré) :'],
  ['b', '**Non-directif** : introspection du répondant ; peu structuré, peu d’interactions avec l’enquêteur.'],
  ['b', '**Semi-directif** : structure globale (guide d’entretien) mais réponses libres.'],
  ['b', '**Directif** : questions très orientées ; très structuré, l’enquêteur intervient beaucoup.'],
  ['p', '**Les entretiens de groupe** – le **focus group** : investigation semi-structurée, un seul thème familier au groupe, réunion dans un même lieu (ou en ligne), **6 à 12 membres, 2 à 4 heures**. Autres méthodes : groupe nominal (plus structuré), groupe de créativité (type brainstorming), groupe Delphi (plus structuré, composé d’experts).'],
  ['p', '**c) Les méthodes projectives**'],
  ['table', ['Méthode', 'Principe'], [
    ['Association d’idées', 'Donner tous les mots qui viennent spontanément à l’esprit à l’évocation d’une marque, d’une pub…'],
    ['Association d’images', 'Associer des images à des marques ou produits (ex. personnages stéréotypés et marques de voitures)'],
    ['Tests d’expression', 'Compléter des phrases inachevées'],
    ['Aperceptions thématiques', 'Interpréter une situation volontairement ambiguë (ex. dans quelle situation le personnage a le plus envie de fumer)'],
    ['Méthodes analogiques', '« Si telle marque était une couleur / un animal / un pays… »'],
    ['Méthodes créatives', 'Jeux de rôle, histoires à compléter, personnification d’une marque, arts plastiques'],
  ]],
  ['p', '**Études quantitatives – échantillonnage**'],
  ['table', ['Méthode', 'Principe'], [
    ['Aléatoire simple', 'Tirage au sort dans une base de données'],
    ['Stratifié', 'On divise la population par tranches (âge, sexe, région) puis on tire dans chaque strate'],
    ['Par quotas', 'On interroge selon des proportions définies (ex. 50 % femmes, 50 % hommes)'],
    ['Par convenance', 'On interroge les personnes facilement accessibles (peu rigoureux)'],
  ]],
  ['p', '**Types de questions** : ouverte (« Que pensez-vous des fast-foods ? ») ; fermée à choix unique (tranche d’âge) ; fermée à choix multiples (quels fast-foods consommez-vous ?) ; échelle de Likert (de 1 « pas du tout d’accord » à 7 « tout à fait d’accord ») ; échelle de fréquence (jamais, rarement, souvent, très souvent).'],
  ['p', '**A/B test** : on présente deux versions (A et B) d’un même élément (packaging, page web…) à deux groupes comparables et on mesure laquelle performe le mieux.'],
  ['p', '**Panels et baromètres** : interrogations répétées dans le temps (même échantillon pour le panel) pour suivre les évolutions.'],

  ['ret', [
    'PESTEL = macro-environnement ; 5 forces de Porter = secteur ; SWOT = synthèse interne/externe.',
    'Part de marché = ventes de l’entreprise / ventes totales du marché × 100.',
    'Marché potentiel = clients actuels + clients des concurrents + non-consommateurs relatifs.',
    'Taux de pénétration = marché réel / marché potentiel.',
    'Documentaire = données secondaires ; qualitatif = comprendre ; quantitatif = mesurer.',
    'Focus group : 6 à 12 personnes, 2 à 4 h, un seul thème.',
  ]],

  // ---------------------------------------------------------------------
  ['h2', '2. Marketing stratégique'],
  ['p', 'La démarche **SCP** (en anglais STP) :'],
  ['table', ['Segmentation', 'Ciblage', 'Positionnement'], [
    ['Identifier des groupes de clients', 'Choisir un ou plusieurs segments', 'Définir son offre pour chaque segment'],
  ]],

  ['h3', '2.1 La segmentation'],
  ['p', 'Découper le marché en sous-groupes homogènes de consommateurs.'],
  ['table', ['Démographiques', 'Socio-économiques', 'Géographiques', 'Psychographiques'], [
    ['Genre, âge, caractéristiques physiques, ethnie, cycle de vie', 'Revenu, éducation, profession, taille du foyer, statut social', 'Ville, pays, densité, langage, climat, population', 'Valeurs, croyances, intérêts, opinions, style de vie (lifestyle)'],
  ]],
  ['p', '**Autres critères (comportementaux)** : quantités consommées, modes de consommation, situations / degré d’implication, statut utilisateur / fidélité, avantages recherchés.'],
  ['p', '**Focus segmentation RFM** : on segmente les clients selon la **R**écence du dernier achat, la **F**réquence d’achat et le **M**ontant dépensé. Exemple du cours : les donateurs d’une association répartis en segments (fidèles en prélèvement automatique, nouveaux, inactifs, généreux, puis « moyens » et « petits » donateurs selon leur fréquence).'],
  ['p', '**Choix des critères** : segmentation multicritère, sélection a priori (critères choisis à l’avance), typologie (groupes construits a posteriori à partir des données).'],
  ['p', '**Une bonne segmentation** : pertinence des critères, **différenciation inter-segments** (les segments sont différents entre eux), **homogénéité intra-segment** (les membres d’un segment se ressemblent).'],

  ['h3', '2.2 Le ciblage'],
  ['p', 'Sélectionner les bons segments selon deux critères : leur **attractivité** (taille, croissance, rentabilité) et la **faisabilité** (l’entreprise a-t-elle les moyens de les servir ?). La cible peut être incarnée par un **persona** (fiche décrivant un client type).'],
  ['img', 'c1_47.png', 15, 'Les quatre stratégies de ciblage'],
  ['b', '**Marketing indifférencié (de masse)** : une seule offre pour tout le marché.'],
  ['b', '**Marketing différencié / segmenté** : une offre adaptée à chaque segment.'],
  ['b', '**Marketing concentré (de niche)** : une offre pour un seul segment.'],
  ['b', '**Marketing personnalisé / individualisé** : une offre par client.'],

  ['h3', '2.3 Le positionnement'],
  ['p', '**Positionnement = intention** (ce que la marque veut qu’on pense d’elle) ≠ **image = résultat** (ce qu’on pense réellement de la marque).'],
  ['p', '**Étape 1 – Identification** : choisir son univers de référence (Apéricube : fromage ou apéro ?). Y a-t-il assez de demande ? Peut-on faire mieux que les concurrents ? Est-on crédible sur ce marché ?'],
  ['p', '**Étape 2 – Différenciation** à l’aide du **triangle d’or du positionnement** :'],
  ['img', 'c1_51.png', 6.5, 'Le triangle d’or du positionnement'],
  ['p', '**Sources de différenciation** (exemples du cours) : fonctionnelle (Dyson), par le prix (easyJet), par le design (Apple), émotionnelle (Coca-Cola), par les services (Amazon).'],
  ['p', '**Cas particulier des MDD** (marques de distributeur) : elles se positionnent souvent par imitation des marques leaders, à prix inférieur.'],
  ['p', '**Le mapping** (carte perceptuelle) : on place les marques sur deux axes (ex. prix bas/élevé et goût/santé pour les yaourts) pour repérer les positions libres.'],
  ['img', 'c1_54.png', 8, 'Mapping du marché des yaourts'],
  ['p', '**Conditions d’un bon positionnement** : Simple, Attractif, Crédible, Différent, Profitable, Durable (Sustainable).'],
  ['p', '**Phrase de positionnement** : « [La marque X] propose à [telle cible] un [catégorie de produits] ayant [telles caractéristiques] qui leur offre [tels bénéfices]. »'],

  ['ret', [
    'Segmentation → ciblage → positionnement.',
    'Bonne segmentation : critères pertinents, hétérogénéité entre segments, homogénéité dans chaque segment.',
    'RFM = Récence, Fréquence, Montant.',
    'Ciblage : indifférencié, différencié, concentré, personnalisé.',
    'Positionnement (intention) ≠ image (résultat). Triangle d’or : attentes des consommateurs, atouts du produit, positionnement des concurrents.',
    'Bon positionnement : simple, attractif, crédible, différent, profitable, durable.',
  ]],

  // ---------------------------------------------------------------------
  ['h2', '3. La marque'],

  ['h3', '3.1 Aspect juridique'],
  ['b', '**Choisir la marque** : elle doit être licite, distinctive et disponible.'],
  ['b', '**Déposer la marque** auprès de l’**INPI**, en choisissant les produits concernés.'],
  ['b', '**Surveiller et défendre la marque** : usage, contrefaçon.'],
  ['p', 'Le dépôt confère un **titre de propriété de 10 ans, renouvelable indéfiniment**.'],

  ['h3', '3.2 Avantages d’une bonne marque'],
  ['p', 'Donner confiance, permettre l’identification, donner du sens.'],

  ['h3', '3.3 Le capital de marque'],
  ['p', 'Une marque a une valeur : deux t-shirts blancs quasi identiques se vendent 5 € ou 50 € selon la marque. Le capital de marque est :'],
  ['b', '**un actif intangible**, qui peut être positif ou négatif ;'],
  ['b', '**basé sur des représentations mentales** : notoriété de la marque, associations et image de marque, performances et qualité perçue, attachement et fidélité ;'],
  ['b', '**créateur de valeur** pour les consommateurs et pour l’entreprise.'],
  ['img', 'c1_62.png', 11, 'Les quatre composantes du capital de marque'],

  ['h3', '3.4 Le branding'],
  ['p', 'Le **branding** regroupe les actions qui construisent le capital de marque.'],
  ['p', '**L’identité de marque**'],
  ['table', ['Physiologie', 'Psychologie', 'Sociologie'], [
    ['Signes et éléments concrets qui permettent de reconnaître la marque (nom, logo, couleurs, jingle…)', 'Traits humains attribués à la marque (sincérité, excitation, compétence, raffinement, robustesse)', 'Convictions profondes qui guident les choix et la communication (confiance, intégrité, bienveillance, respect, tradition…)'],
  ]],
  ['p', '**Architecture de marque**'],
  ['img', 'c1_65.png', 13, 'Architecture de marque : l’exemple de The Coca-Cola Company'],
  ['b', '**Marque mère (ou corporate)** : l’entreprise (The Coca-Cola Company).'],
  ['b', '**Marque ombrelle (ou marque famille)** : couvre plusieurs produits (Coca-Cola).'],
  ['b', '**Marques filles / individuelles** : une marque propre par produit (Sprite, Fanta).'],
  ['b', '**Marques produits (sous-marques)** : déclinaisons (Coca-Cola Zero, Cherry…).'],
  ['p', 'Trois stratégies : **monolithique (Branded House)** – tout est vendu sous un même nom ; **individuelle (House of Brands)** – une marque par produit (Unilever : Dove, Axe, Magnum…) ; **hybride** – mélange des deux.'],
  ['p', '**Extension de marque** : utiliser une marque existante pour un nouveau produit (Bonne Maman : de la confiture aux madeleines). Types : extension de ligne, de gamme, verticale, horizontale.'],
  ['p', '**Co-branding** : association de deux marques (DOP × Haribo). Types : co-branding produit, de communication, d’alliance.'],
  ['p', '**Évolution de la marque** : **modernisation** (évolution progressive du logo : Starbucks, Apple, Audi, Coca-Cola) ou **rebranding** (changement profond : Dunkin’ Donuts → Dunkin’, Burberry, Airbnb).'],

  ['ret', [
    'Marque : licite, distinctive, disponible ; dépôt INPI ; protection 10 ans renouvelable indéfiniment.',
    'Capital de marque = notoriété + image + qualité perçue + fidélité → valeur pour le consommateur et l’entreprise.',
    'Identité : physiologie (signes), psychologie (personnalité), sociologie (valeurs).',
    'Architecture : Branded House (monolithique), House of Brands (individuelle), hybride.',
    'Modernisation (évolution douce) ≠ rebranding (changement profond).',
  ]],

  // =====================================================================
  ['h1', 'Partie 2 – Le prix'],
  // =====================================================================
  ['p', 'Le prix est le 2e « P » du marketing mix. Le cours s’ouvre sur six cas qui montrent qu’un prix est aussi une perception :'],
  ['b', '**Cas 1** : deux sacs identiques à 20 € et 200 € – lequel paraît de meilleure qualité ? (le prix sert de signal de qualité)'],
  ['b', '**Cas 2** : un iPhone passe de 1 630 € à 1 690 € – l’achète-t-on toujours ? (élasticité)'],
  ['b', '**Cas 3** : deux boulangeries vendent à 2,50 € ; la B fait 1 € de marge contre 0,50 € pour la A – où va-t-on ? (justice perçue)'],
  ['b', '**Cas 4 à 6** : le prix est-il juste ? Patagonia ou Shein, laquelle croit-on quand elle justifie une hausse de 10 % par l’environnement ? Malongo augmente de 3,50 € à 3,90 € pour mieux rémunérer les agriculteurs.'],

  ['h2', '1. La politique de prix dans le mix'],
  ['b', 'Le prix est le **seul élément du mix qui génère directement du revenu**.'],
  ['b', 'Facteur clé de compétitivité et de positionnement perçu.'],
  ['b', 'Double objectif : **couvrir les coûts** de l’entreprise et **satisfaire la demande** tout en restant compétitif.'],
  ['b', 'Triple dimension : économique, stratégique et psychologique.'],
  ['p', 'Le prix se situe entre un **minimum** (rentabilité : il doit couvrir les coûts) et un **maximum** (acceptabilité : il doit être accepté par les clients).'],

  ['h2', '2. Fixer un prix – l’approche par les coûts'],
  ['h3', '2.1 Les différents coûts'],
  ['b', '**Coûts directs** : imputables de manière claire et exclusive à un produit.'],
  ['b', '**Coûts indirects** : concernent plusieurs produits ; répartis grâce à des clés de répartition.'],
  ['b', '**Coûts fixes** : constants quel que soit le volume des ventes (directs ou indirects).'],
  ['b', '**Coûts variables** : varient proportionnellement à la production/aux ventes (directs ou indirects).'],
  ['table', ['', 'Fixes', 'Variables'], [
    ['Directs', 'Location d’une salle pour un concert ; moule spécifique à un modèle de chaussure ; licence logicielle pour un jeu vidéo', 'Carburant d’un trajet de bus précis ; tissu d’une robe ; papier et encre d’un livre'],
    ['Indirects', 'Loyer d’un supermarché ; salaire du directeur d’un hôpital ; système de sécurité d’une usine multi-produits', 'Électricité d’une usine ; entretien des rails lié à la circulation des trains'],
  ]],

  ['h3', '2.2 Calcul du coût'],
  ['p', '**Coût moyen = Coût total / Nombre d’unités produites** (coût « standard » par unité).'],
  ['p', '**Coût marginal** = supplément de coût engendré par la vente d’une unité supplémentaire. **Coût marginal ≠ coût moyen** ; **coût marginal ≈ coût variable direct d’une unité**.'],
  ['p', '**Exemple de la boulangerie** (sur un mois, 50 baguettes/jour, 20 jours = 1 000 baguettes) :'],
  ['table', ['Coût', 'Montant', 'Nature'], [
    ['Location du local', '800 €/mois', 'Fixe indirect'],
    ['Électricité', '600 €/mois', 'Variable indirect'],
    ['Four à pain', '—', 'Fixe direct'],
    ['Ingrédients', '500 €/semaine', 'Variable direct'],
    ['Emballage', '200 €/semaine', 'Variable direct'],
    ['Salaires', '1 800 €/mois × 2', 'Fixe indirect'],
  ]],
  ['b', '**Coûts totaux** (ramenés au mois) = 800 + 600 + 500×4 + 200×4 + 3 600 = **7 800 €**.'],
  ['b', '**Coût moyen** = 7 800 / 1 000 = **7,80 €** par baguette.'],
  ['b', '**Coût marginal** (diapo) = (ingrédients 500 + emballage 200) / 1 000 ≈ **0,70 €**.'],
  ['note', 'Attention : la diapo calcule le coût total avec les ingrédients et l’emballage à la semaine (×4), mais le coût marginal avec ces mêmes montants au mois. Avec des montants hebdomadaires, on obtiendrait (2 000 + 800) / 1 000 = 2,80 €. Retiens la méthode et vérifie le chiffre attendu avec ta professeure.'],

  ['h3', '2.3 Variation du coût unitaire'],
  ['p', '**Effet d’expérience et économies d’échelle** : plus on produit, moins chaque unité coûte cher, grâce à un meilleur pouvoir de négociation, à l’amélioration des compétences et de la productivité, et à des équipements plus performants (automatisation).'],

  ['h3', '2.4 Fixer son prix en appliquant une marge'],
  ['p', 'La marge se décide selon des **objectifs marketing** (rentabilité = marge élevée ; prix d’appel = marge faible voire nulle) ou selon des **normes internes** (généralement en % du prix de vente).'],
  ['p', '**Prix de vente = Prix de revient / (1 – taux de marge)**. Exemple : coût de 7,80 € et marge de 20 % du prix de vente → 7,80 / 0,80 = 9,75 €.'],
  ['p', '**Point mort** = nombre d’unités à vendre pour que les recettes couvrent les frais fixes. Il permet de fixer un objectif de volume de ventes.'],

  ['h2', '3. Fixer un prix – l’approche par la demande'],
  ['p', 'Principe enraciné dans la loi de l’offre et de la demande (Adam Smith, 1776).'],
  ['p', '**Élasticité-prix de la demande = (ΔD / D) / (ΔP / P)** : de combien (en %) la demande varie quand le prix varie de 1 %.'],
  ['p', 'Exemple : 1 000 unités vendues à 100 € ; à 110 € (+10 %), les ventes tombent à 850 (–15 %). Élasticité = –15 % / +10 % = **–1,5**.'],
  ['table', ['Élasticité', 'Signification', 'Exemples'], [
    ['Négative (cas courant)', 'Hausse du prix → baisse de la demande', 'Vêtements, cinéma'],
    ['Nulle', 'Demande insensible au prix', 'Insuline, péages obligatoires'],
    ['Positive (rare)', 'Effet de « snobisme » : la demande augmente avec le prix', 'Sacs Hermès, grands crus'],
  ]],
  ['p', '**L’élasticité est influencée par** : la nature de l’achat, le rôle du payeur, la facilité à trouver un substitut, la hiérarchie des critères d’achat, le niveau d’implication de l’acheteur.'],

  ['h2', '4. Fixer un prix – la perception des acheteurs'],
  ['p', '**Positionnement prix** : bas de gamme (low-end), premium, haut de gamme et luxe. Le prix joue un rôle de signal de qualité (cas 1 : le sac à 200 € paraît meilleur).'],

  ['h2', '5. Stratégies de fixation du prix'],
  ['table', ['Stratégie', 'Principe / exemple du cours'], [
    ['Segmentation', 'Prix différents selon les segments (tarifs jeunes, seniors…)'],
    ['Écrémage (price skimming)', 'Prix élevé au lancement, baissé ensuite (iPhone)'],
    ['Free access', 'Accès gratuit, revenus ailleurs (jeux mobiles, YouTube)'],
    ['Dynamic pricing', 'Prix qui varie en temps réel selon la demande'],
    ['Faire participer les acheteurs', 'Pick your own price, pay what you want, enchères'],
    ['Stratégies de fidélité', 'Location, abonnement (vélos en libre-service, salle de sport)'],
    ['Modes de paiement', 'Paiement différé ou fractionné (3×, 4×), espèces'],
    ['Les chiffres', 'Prix psychologiques : 0,99 € au lieu de 1,00 €'],
  ]],

  ['h2', '6. L’évaluation d’un prix : la justice perçue'],
  ['p', '**Définition** : la justice perçue d’un prix est « un jugement visant à déterminer si un résultat et/ou le processus permettant d’y parvenir sont raisonnables, acceptables ou justes » (Xia et al., 2004).'],
  ['b', 'C’est le résultat d’un **processus comparatif**…'],
  ['b', '… reposant sur des **principes d’équité** (Adams, 1965) : un prix est jugé juste si **Contributions de l’acheteur / Avantages de l’acheteur = 1**.'],
  ['p', '**Comparaison à un prix de référence** : aux autres acheteurs ou au(x) vendeur(s). Trois situations possibles : **égalité**, **inégalité avantageuse**, **inégalité désavantageuse**.'],
  ['b', '**Prix de référence internes** (prix payés dans le passé) et **externes** (prix d’un autre produit) ; idem pour les **points de référence** (ex. les coûts).'],
  ['p', '**Ce qui influence le jugement de justice** :'],
  ['b', 'Les **coûts et profits estimés du vendeur** (cas 3 : même prix, mais la boulangerie qui marge davantage paraît moins juste).'],
  ['b', 'La **procédure de fixation du prix** (Maxwell, 2002 : respect perçu des règles d’un prix juste → attitude envers le vendeur → intention d’achat).'],
  ['b', 'La **moralité du prix**.'],
  ['b', 'Tous les coûts et tous les profits ne sont pas jugés justes.'],
  ['b', 'Une perception influençable par : la **réputation** de la marque, l’**origine** de la marque, les **attitudes** des acheteurs.'],

  ['h2', '7. Le cas des hausses de prix'],
  ['b', 'Une justification par les coûts est mieux acceptée… mais pas par tous les coûts : les **coûts externes et incontrôlables** sont mieux acceptés.'],
  ['b', 'Les coûts invoqués doivent être **alignés au produit**.'],
  ['b', 'La **réputation de l’entreprise** est déterminante (cas 5 : on croit davantage Patagonia que Shein).'],

  ['h2', '8. Stratégies de communication du prix'],
  ['b', '**Annonce d’un prix de référence** : prix barré (ex. forfaits mobiles).'],
  ['b', '**Comparaisons de prix** : avec les concurrents (ex. campagnes comparatives de la grande distribution).'],
  ['b', '**Transparence** : détailler la répartition du prix (ex. lait « C’est qui le patron ?! » et la rémunération du producteur).'],
  ['p', '**Pour conclure** : la juste rémunération des producteurs agricoles est plus qu’un coût pour les acheteurs ; elle peut devenir un argument de valeur.'],

  ['ret', [
    'Le prix est le seul élément du mix qui rapporte directement ; il est borné par la rentabilité (min.) et l’acceptabilité (max.).',
    'Coûts : directs/indirects × fixes/variables. Coût moyen = coût total / quantité ; coût marginal ≈ coût variable direct unitaire.',
    'Prix de vente = prix de revient / (1 – taux de marge). Point mort = volume qui couvre les frais fixes.',
    'Élasticité = %ΔD / %ΔP ; négative (courant), nulle, positive (snobisme).',
    'Justice perçue (Xia et al., 2004) ; équité (Adams, 1965) : contributions / avantages = 1.',
    'Communication du prix : prix de référence, comparaison, transparence.',
  ]],

  // =====================================================================
  ['h1', 'Partie 3 – CM 6 : le marketing mix (produit et distribution)'],
  // =====================================================================
  ['p', 'Le marketing mix (les « 4P ») regroupe les décisions opérationnelles :'],
  ['table', ['Product (produit)', 'Price (prix)', 'Place (distribution)', 'Promotion (communication)'], [
    ['Caractéristiques, design, qualité, gamme, packaging', 'Niveau de prix, remises, conditions de paiement, stratégie tarifaire', 'Canaux, couverture, logistique, points de vente', 'Publicité, promotion des ventes, relations publiques, influence'],
  ]],
  ['p', 'Le prix a été traité dans la Partie 2 ; la communication sera vue dans un prochain cours.'],

  ['h2', '4.1 Le produit'],
  ['h3', 'Nature du produit'],
  ['p', '**Catégories** : biens de grande consommation, biens industriels, services, prestations et objets culturels.'],
  ['p', 'Une offre est **un mélange de biens et de services**, sur un continuum du tangible à l’intangible : biens purement matériels (produits alimentaires) → biens accompagnés d’un service (photocopieur avec maintenance) → bien matériel support d’une offre intangible (smartphone, presse) → mise à disposition de biens (location) → services s’appuyant sur des éléments matériels (restauration, hôtellerie, transports) → services purement immatériels (services financiers, conseil).'],
  ['p', '**Processus d’achat** : biens/services courants ; d’achat réfléchi ; de spécialité ; non recherchés / non sollicités.'],

  ['h3', 'Les 5 niveaux de produit'],
  ['img', 'c3_6.png', 6, 'Les 5 niveaux de produit'],
  ['b', '**Bénéfice central (core benefit)** : le besoin fondamental satisfait.'],
  ['b', '**Produit de base (basic)** : la version élémentaire qui délivre ce bénéfice.'],
  ['b', '**Produit attendu (expected)** : ce que le client s’attend normalement à trouver.'],
  ['b', '**Produit augmenté (augmented)** : ce qui dépasse les attentes et différencie.'],
  ['b', '**Produit potentiel (potential)** : les évolutions futures possibles.'],

  ['h3', 'Différencier son produit'],
  ['p', 'Quatre leviers : **performances, design, services associés, packaging**. L’avantage compétitif doit : être une réponse crédible à une attente réelle, être facilement perceptible ou communicable, avoir un prix acceptable, être difficilement imitable.'],
  ['b', '**Performances** : efficacité, fiabilité, durabilité, sécurité, efficience.'],
  ['b', '**Design** : esthétique (forme, couleur, texture, style) et ergonomie (utilité, facilité, confort, adaptabilité).'],
  ['b', '**Services associés** : avant l’achat (conseils, démonstrations, essai), pendant (facilités de paiement, livraison, installation), après (garanties, retours, SAV, maintenance).'],
  ['b', '**Packaging** : fonctions techniques (préservation et protection, stockage/transport/mise en rayon, facilité d’usage, impact environnemental) et fonctions de communication (information, impact visuel, identification du produit et de la marque, expression du positionnement).'],
  ['p', 'À retenir : **un bon produit n’est pas forcément « le meilleur produit »**.'],

  ['h3', 'Innovation et diffusion'],
  ['p', '**Types d’innovation** : incrémentale (amélioration d’un produit existant), adjacente, de rupture, radicale (ex. le premier iPhone).'],
  ['p', '**Diffusion des innovations** (courbe en cloche) : innovateurs **2,5 %**, adopteurs précoces **13,5 %**, majorité précoce **34 %**, majorité tardive **34 %**, retardataires **16 %**.'],
  ['img', 'c3_14.png', 10, 'La diffusion des innovations'],

  ['h3', 'Le cycle de vie des produits'],
  ['p', 'Quatre phases : **lancement** (ventes faibles, pertes), **développement** (forte croissance, le profit apparaît), **maturité** (ventes maximales, stabilisées), **déclin**.'],
  ['img', 'c3_15.png', 10, 'Le cycle de vie du produit (ventes et profit)'],

  ['h3', 'La politique de gamme'],
  ['b', '**Largeur** = nombre de lignes de produits.'],
  ['b', '**Profondeur** = nombre de produits dans une ligne.'],
  ['b', '**Longueur** = somme de tous les produits de toutes les lignes.'],
  ['p', '**Types de produits dans une gamme** : produits leaders, d’appel, d’image, pour l’avenir, régulateurs, tactiques. **Niveaux de gamme** : bas de gamme, entrée de gamme, moyen de gamme, haut de gamme.'],

  ['h3', 'Outils d’analyse du portefeuille'],
  ['p', '**La matrice BCG** croise le **taux de croissance du marché** et la **part de marché relative** :'],
  ['img', 'c3_17.png', 7, 'La matrice BCG'],
  ['table', ['Case', 'Croissance', 'PDM relative', 'Rôle'], [
    ['Vedettes', 'Forte', 'Forte', 'Produits à soutenir, futurs vaches à lait'],
    ['Dilemmes', 'Forte', 'Faible', 'Investir ou abandonner'],
    ['Vaches à lait', 'Faible', 'Forte', 'Génèrent des liquidités'],
    ['Poids morts', 'Faible', 'Faible', 'Candidats à l’abandon'],
  ]],
  ['p', '**La règle des 80/20 (Pareto)** : environ 20 % des produits réalisent 80 % du chiffre d’affaires.'],
  ['p', '**La longue traîne (en ligne)** : sur Internet, la multitude de références peu vendues peut, cumulée, représenter un chiffre d’affaires important.'],
  ['p', '**La cannibalisation** : un nouveau produit prend des ventes à un produit de la même entreprise (ex. les nombreuses marques de yaourts de Danone).'],

  ['h2', '4.3 La distribution'],
  ['h3', 'Définition et fonctions'],
  ['p', 'Distribuer ses produits, c’est les apporter **aux bons clients, au bon endroit, au bon moment, en quantité suffisante et dans le bon format** (assortiment, services, entretien). La distribution gère trois flux entre producteur et consommateur : **physiques, d’informations, financiers**.'],
  ['table', ['Logistique', 'Information', 'Communication', 'Contact et service'], [
    ['Transport, stockage, gestion des stocks', 'Collecte et diffusion des données marché', 'Affichage des prix, promotion sur le point de vente', 'Conseil, installation, SAV, livraison'],
  ]],
  ['p', 'Le canal choisi est un **levier du positionnement** : il influence l’image et la valeur perçue.'],

  ['h3', 'Acteurs et circuits'],
  ['table', ['Acteur', 'Rôle'], [
    ['Producteurs / fabricants', 'Créent le produit'],
    ['Grossistes', 'Achètent en grande quantité et revendent aux détaillants'],
    ['Détaillants / points de vente', 'Vendent directement au consommateur'],
    ['Plateformes / marketplaces', 'Facilitent la mise en relation et la vente'],
    ['Agents et courtiers', 'Intermédiaires spécialisés, sans stock propre'],
  ]],
  ['img', 'c3_27.png', 11, 'Vente directe, circuit court, circuit long'],
  ['b', '**Vente directe** : aucun intermédiaire.'],
  ['b', '**Circuit court** : un seul intermédiaire (ex. détaillant).'],
  ['b', '**Circuit long** : au moins deux intermédiaires (ex. grossiste + détaillant).'],
  ['p', '**Contraintes liées aux intermédiaires** : conflits (verticaux entre niveaux du circuit / horizontaux entre membres d’un même niveau), rapports de pouvoir, dépendance, négociation.'],

  ['h3', 'Types de commerce'],
  ['table', ['Commerce indépendant', 'Commerce intégré', 'Commerce associé'], [
    ['Commerçants autonomes, propriétaires de leur point de vente', 'Points de vente appartenant à une même entreprise (grands magasins, GMS, GSS, hard discount)', 'Entreprises juridiquement indépendantes qui s’unissent (coopératives, franchises)'],
  ]],
  ['p', '**La franchise** : partenariat dans lequel le **franchiseur** (la marque) permet au **franchisé** (l’entrepreneur) d’exploiter sa marque, son savoir-faire et son modèle. Le franchiseur apporte marque, savoir-faire, formation et soutien ; le franchisé paie un droit d’entrée et des redevances sur le CA et respecte le concept. Le **contrat de franchise** fixe les droits et obligations (durée, zone d’exclusivité, redevance…).'],

  ['h3', 'Stratégies et choix des canaux'],
  ['table', ['Intensive', 'Sélective', 'Exclusive'], [
    ['Être présent partout (Coca-Cola)', 'Points de vente choisis selon des critères (Clarins en parfumerie)', 'Très peu de points de vente, souvent en exclusivité (Rolex)'],
  ]],
  ['p', '**Critères de choix des canaux** : nature du produit et de la clientèle, coûts et capacité logistique, image de marque et positionnement, couverture géographique et volume.'],

  ['h3', 'Décisions liées au point de vente'],
  ['p', '**1. Implantation** selon la **zone de chalandise** (aire géographique d’où provient l’essentiel de la clientèle potentielle, qu’elle y vive ou y travaille).'],
  ['b', 'Magasins indépendants : centre-ville (fort trafic, visibilité, loyers élevés), périurbain (accès voiture, grandes surfaces, loyers plus bas), zones marchandes (regroupement de commerces spécialisés).'],
  ['b', 'Centres commerciaux : forte attractivité et flux garanti, mais contraintes élevées.'],
  ['p', '**2. Assortiment** (exemple de la grande distribution) :'],
  ['table', ['Marques nationales leaders', 'Marque de distributeur (MDD)', 'Premier prix'], [
    ['Forte notoriété et image (Coca-Cola, Nutella) ; génèrent du trafic et crédibilisent l’offre ; marges souvent plus faibles pour le distributeur', 'Développée par l’enseigne (Marque Repère, Reflets de France) ; prix moyen, bonne qualité perçue ; meilleure marge, fidélisation, différenciation', 'Produits très accessibles, faible marge unitaire (Eco+) ; clientèle sensible au prix ; « prix d’appel »'],
  ]],
  ['p', '**3. Merchandising** : ensemble des techniques qui optimisent la présentation des produits en magasin pour maximiser les ventes et améliorer l’expérience client. Leviers : organisation de l’espace (rayons, circulation), mise en valeur du produit (linéaires, têtes de gondole, vitrines), signalétique et ambiance (éclairage, couleurs, odeurs, musique).'],
  ['p', '**4. Niveau de service et de personnel** : accueil, prise en charge (parking, enfants), information et conseil, prise de commande, paiement, livraison, maintenance, réclamations, programme de fidélisation…'],

  ['h3', 'Multicanal et e-commerce'],
  ['p', 'Un seul canal suffit rarement. En e-commerce, on distingue les **pure players** (100 % en ligne, ex. Amazon) et les **click and mortar** (enseignes physiques qui ajoutent un canal en ligne, ex. Fnac).'],
  ['p', '**Modèles économiques** : marchand (le site vend ses propres produits, ex. Zara) ; média / marketplace (le site met en relation acheteurs et vendeurs, ex. eBay) ; hybride (Amazon vend ses produits et héberge d’autres vendeurs).'],
  ['p', '**Tunnel d’achat** : toutes les étapes du parcours client : attirer (inconnu → visiteur), intéresser (→ prospect), convertir (→ client), fidéliser (→ ambassadeur). Objectif : faciliter chaque étape pour maximiser la conversion.'],
  ['p', '**Le client transcanal** :'],
  ['table', ['', 'Achat hors ligne', 'Achat en ligne'], [
    ['Recherche en ligne', 'ROPO (Research Online, Purchase Offline)', 'Full digital'],
    ['Recherche hors ligne', 'Full store', 'Showrooming'],
  ]],
  ['img', 'c3_42.png', 11, 'Canal simple, multicanal, cross-canal, omnicanal'],
  ['b', '**Canal simple** : un seul canal.'],
  ['b', '**Multicanal** : plusieurs canaux qui fonctionnent séparément.'],
  ['b', '**Cross-canal** : les canaux sont reliés (ex. commander en ligne, retirer en magasin).'],
  ['b', '**Omnicanal** : tous les canaux sont intégrés et le client passe de l’un à l’autre sans rupture.'],

  ['ret', [
    '4P : produit, prix, distribution (place), communication (promotion).',
    '5 niveaux : bénéfice central, produit de base, attendu, augmenté, potentiel.',
    'Diffusion : 2,5 / 13,5 / 34 / 34 / 16 %. Cycle de vie : lancement, développement, maturité, déclin.',
    'Gamme : largeur (lignes), profondeur (produits par ligne), longueur (total).',
    'BCG : vedettes, dilemmes, vaches à lait, poids morts. Pareto : 20 % des produits = 80 % du CA.',
    'Circuits : direct (0), court (1), long (2+) intermédiaires. Distribution intensive, sélective, exclusive.',
    'ROPO = recherche en ligne, achat en magasin ; showrooming = l’inverse.',
  ]],

  // =====================================================================
  ['h1', 'Glossaire'],
  // =====================================================================
  ['glo', 'A/B test', 'Comparaison de deux versions d’un élément auprès de deux groupes pour identifier la plus performante.'],
  ['glo', 'Architecture de marque', 'Organisation des marques d’une entreprise : monolithique (Branded House), individuelle (House of Brands) ou hybride.'],
  ['glo', 'Capital de marque', 'Valeur intangible d’une marque fondée sur sa notoriété, son image, sa qualité perçue et la fidélité qu’elle suscite.'],
  ['glo', 'Cannibalisation', 'Perte de ventes d’un produit au profit d’un autre produit de la même entreprise.'],
  ['glo', 'Ciblage', 'Choix du ou des segments que l’entreprise va servir.'],
  ['glo', 'Circuit court / long', 'Circuit à un seul intermédiaire / à au moins deux intermédiaires.'],
  ['glo', 'Co-branding', 'Association de deux marques autour d’un produit, d’une communication ou d’une alliance.'],
  ['glo', 'Coût marginal', 'Coût supplémentaire lié à la production/vente d’une unité de plus ; proche du coût variable direct unitaire.'],
  ['glo', 'Coût moyen', 'Coût total divisé par le nombre d’unités produites.'],
  ['glo', 'Cycle de vie du produit', 'Succession des phases de lancement, développement, maturité et déclin.'],
  ['glo', 'Dissonance cognitive', 'Inconfort psychologique ressenti après un achat lorsque des doutes apparaissent.'],
  ['glo', 'Écrémage', 'Stratégie de prix élevé au lancement, réduit ensuite.'],
  ['glo', 'Élasticité-prix', 'Variation en % de la demande pour une variation de 1 % du prix.'],
  ['glo', 'Extension de marque', 'Utilisation d’une marque existante pour lancer un nouveau produit.'],
  ['glo', 'Focus group', 'Entretien de groupe semi-structuré (6 à 12 personnes, 2 à 4 h) sur un thème.'],
  ['glo', 'Franchise', 'Contrat par lequel un franchiseur cède l’usage de sa marque et de son savoir-faire à un franchisé contre redevances.'],
  ['glo', 'Hiérarchie des effets', 'Enchaînement cognitif (connaître) → affectif (aimer) → conatif (agir).'],
  ['glo', 'Image de marque', 'Ce que les consommateurs pensent réellement de la marque (résultat).'],
  ['glo', 'Implication', 'Degré d’importance accordé par le consommateur à une décision d’achat.'],
  ['glo', 'Justice perçue du prix', 'Jugement sur le caractère raisonnable, acceptable ou juste d’un prix et de sa fixation (Xia et al., 2004).'],
  ['glo', 'Longue traîne', 'Poids cumulé, en ligne, des nombreuses références peu vendues.'],
  ['glo', 'Mapping', 'Carte perceptuelle plaçant les marques sur deux axes pour visualiser les positionnements.'],
  ['glo', 'Marché potentiel', 'Clients actuels + clients des concurrents + non-consommateurs relatifs.'],
  ['glo', 'Marché réel', 'Ensemble des clients actuels.'],
  ['glo', 'Matrice BCG', 'Outil d’analyse de portefeuille croisant croissance du marché et part de marché relative.'],
  ['glo', 'MDD', 'Marque de distributeur, créée et vendue par une enseigne.'],
  ['glo', 'Merchandising', 'Techniques d’optimisation de la présentation des produits en point de vente.'],
  ['glo', 'Méthodes projectives', 'Techniques qualitatives faisant projeter au répondant ses pensées (associations, analogies…).'],
  ['glo', 'Non-consommateur absolu / relatif', 'Personne qui ne consommera jamais / qui ne consomme pas encore mais le pourrait.'],
  ['glo', 'Omnicanal', 'Intégration de tous les canaux permettant un parcours client sans rupture.'],
  ['glo', 'Part de marché', 'Ventes de l’entreprise / ventes totales du marché × 100.'],
  ['glo', 'Persona', 'Portrait d’un client type représentant une cible.'],
  ['glo', 'PESTEL', 'Analyse du macro-environnement : politique, économique, socioculturel, technologique, environnemental, légal.'],
  ['glo', 'Point mort', 'Volume de ventes à partir duquel les recettes couvrent les frais fixes.'],
  ['glo', 'Positionnement', 'Place que la marque veut occuper dans l’esprit des cibles (intention).'],
  ['glo', 'Pure player', 'Entreprise dont l’activité est 100 % en ligne.'],
  ['glo', 'RFM', 'Segmentation selon la récence, la fréquence et le montant des achats.'],
  ['glo', 'ROPO', 'Research Online, Purchase Offline : recherche en ligne, achat en magasin.'],
  ['glo', 'Segmentation', 'Découpage du marché en groupes homogènes de consommateurs.'],
  ['glo', 'Showrooming', 'Recherche en magasin, achat en ligne.'],
  ['glo', 'SWOT', 'Synthèse des forces, faiblesses (interne), opportunités et menaces (externe).'],
  ['glo', 'Taux de pénétration', 'Part des clients potentiels ayant acheté au moins une fois sur une période (marché réel / marché potentiel).'],
  ['glo', 'Valeur perçue', 'Bénéfices perçus – coûts perçus.'],
  ['glo', 'Zone de chalandise', 'Aire géographique d’où provient l’essentiel de la clientèle d’un point de vente.'],
];
